using System.Collections;
using UnityEngine;

public class InvertedControls : MonoBehaviour
{
    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Car"))
        {
            Debug.Log("Entr贸 en Trigger con " + other.name);
            PrometeoCarController carController = other.GetComponent<PrometeoCarController>();

            if (carController != null)
            {
                Debug.Log("Encontr贸 el controlador de coche, iniciando inversi贸n.");
                StartCoroutine(ApplyInvertedControls(carController));

                GetComponent<Collider>().enabled = false; 
                GetComponent<Renderer>().enabled = false; 
            }
            else
            {
                Debug.Log("No se encontr贸 el controlador de coche en el objeto.");
            }
        }
    }

    private IEnumerator ApplyInvertedControls(PrometeoCarController carController)
    {
        carController.InvertControls(); // Invertir controles
        Debug.Log("Controles invertidos en el coche.");

        yield return new WaitForSeconds(15); // Esperar 5 segundos

        carController.ResetControls(); // Restaurar controles
        Debug.Log("Controles restaurados en el coche.");
    }
}
